@extends('admin.layout')

@section('title', 'Technical SEO')
@section('page_title', 'Technical SEO')
@section('page_sub', 'Read-only — everything here is generated')

@section('content')

    {{-- Analytics --}}
    <div class="card">
        <div class="card__head">
            <div>
                <div class="card__title">Analytics</div>
                <div class="card__sub">Which tag loader is active, and why</div>
            </div>
            <span class="pill {{ $analytics['loader'] === 'None' ? 'pill--neutral' : 'pill--ok' }}">
                <span class="pill__dot"></span>{{ $analytics['loader'] }}
            </span>
        </div>
        <div class="card__body">
            <p class="small muted" style="margin-bottom:14px;">{{ $analytics['reason'] }}</p>

            <div class="field-row">
                <div>
                    <div class="field__label">GTM_ID</div>
                    <div class="mono">{{ $analytics['gtm_id'] ?: '— not set —' }}</div>
                </div>
                <div>
                    <div class="field__label">GA_ID</div>
                    <div class="mono">{{ $analytics['ga_id'] ?: '— not set —' }}</div>
                    @if($analytics['gtm_id'] && $analytics['ga_id'])
                        <div class="field__hint" style="color:var(--warn);">
                            Ignored while GTM is active, so pageviews cannot double-count.
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {{-- sameAs --}}
    <div class="card" style="margin-top:14px;">
        <div class="card__head">
            <div>
                <div class="card__title">Social profiles (sameAs)</div>
                <div class="card__sub">
                    From <code class="mono">config/seo.php</code>. Tracking parameters are stripped,
                    because sameAs matches on the exact URL.
                </div>
            </div>
        </div>
        <div class="card__body">
            @forelse($sameAs as $network => $url)
                <div class="row" style="padding:7px 0; border-bottom:1px solid var(--line); gap:14px;">
                    <span class="small" style="width:88px; font-weight:600; text-transform:capitalize; flex-shrink:0;">{{ $network }}</span>
                    <code class="mono" style="flex:1; min-width:0; word-break:break-all;">{{ $url }}</code>
                    @if(($rawSocial[$network] ?? '') !== $url)
                        <span class="pill pill--warn">cleaned</span>
                    @endif
                </div>
            @empty
                <p class="muted small"><em>No social profiles configured.</em></p>
            @endforelse
        </div>
    </div>

    {{-- robots.txt --}}
    <div class="card" style="margin-top:14px;">
        <div class="card__head">
            <div>
                <div class="card__title">robots.txt</div>
                <div class="card__sub">Generated by <code class="mono">SitemapController@robots</code></div>
            </div>
            <a href="{{ url('/robots.txt') }}" target="_blank" rel="noopener" class="btn btn--ghost btn--sm">
                View live <i class="fa-solid fa-arrow-up-right-from-square" style="font-size:9px;"></i>
            </a>
        </div>
        <div class="card__body">
            <pre class="mono" style="background:var(--surface-2); border:1px solid var(--line); border-radius:var(--radius); padding:13px; overflow-x:auto; margin:0; line-height:1.6;">{{ $robots }}</pre>
        </div>
    </div>

    {{-- sitemap --}}
    <div class="card" style="margin-top:14px;">
        <div class="card__head">
            <div>
                <div class="card__title">sitemap.xml <span class="muted" style="font-weight:400;">· {{ count($sitemapUrls) }} URLs</span></div>
                <div class="card__sub">
                    Static routes plus active products. <code class="mono">noindex</code> pages are excluded.
                    Blog posts are not included — no blog routes exist yet.
                </div>
            </div>
            <a href="{{ url('/sitemap.xml') }}" target="_blank" rel="noopener" class="btn btn--ghost btn--sm">
                View live <i class="fa-solid fa-arrow-up-right-from-square" style="font-size:9px;"></i>
            </a>
        </div>
        <div class="tablescroll" style="max-height:320px;">
            <table class="table">
                <tbody>
                    @foreach($sitemapUrls as $url)
                        <tr>
                            <td class="mono" style="word-break:break-all;">{{ $url['loc'] }}</td>
                            <td class="table__actions muted small">{{ $url['priority'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    {{-- Graph --}}
    <div class="card" style="margin-top:14px;">
        <div class="card__head">
            <div>
                <div class="card__title">Site-wide structured data</div>
                <div class="card__sub">
                    One <code class="mono">@@graph</code> on every page, from
                    <code class="mono">config/seo.php</code> via <code class="mono">SchemaGraphBuilder</code>.
                    Shown as rendered for the homepage.
                </div>
            </div>
        </div>
        <div class="card__body">
            <pre class="mono" style="background:var(--surface-2); border:1px solid var(--line); border-radius:var(--radius); padding:13px; overflow-x:auto; max-height:400px; margin:0; line-height:1.55;">{{ $graph }}</pre>
        </div>
    </div>

@endsection
